# Generated by Django 5.1.1 on 2025-01-05 22:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeUpStore', '0002_customuser_cod_customuser_email_confirmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('data_expirare', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, help_text='Procentul de reducere (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('descriere', models.TextField()),
                ('categorii', models.ManyToManyField(to='MakeUpStore.categorie')),
            ],
            options={
                'verbose_name': 'Promoție',
                'verbose_name_plural': 'Promoții',
            },
        ),
        migrations.CreateModel(
            name='Vizualizari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MakeUpStore.produs')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vizualizare',
                'verbose_name_plural': 'Vizualizări',
                'ordering': ['-data_vizualizare'],
            },
        ),
    ]
