# Generated by Django 5.1.1 on 2025-01-05 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakeUpStore', '0003_promotie_vizualizari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vizualizari',
            options={'ordering': ['-data_vizualizare']},
        ),
        migrations.AlterField(
            model_name='promotie',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
