# Generated by Django 5.1.1 on 2025-01-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('prenume', models.CharField(max_length=30)),
                ('data_nasterii', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoare', models.IntegerField()),
                ('data_adaugare', models.DateField(auto_now_add=True)),
                ('elev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelExamen.elev')),
            ],
        ),
    ]
